---
- name:  Create user
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ postgresql_user }}"
    password:  "{{ postgres_password }}"

- name: Create db
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ postgresql_user }}"