---


- name: Add postgres key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: Add postgres repo
  apt_repository:
    state: present
    repo: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    update_cache: yes
    filename: postgresql

- name: Install postgres
  apt:
    name: postgresql-16
    state: present
    update_cache: yes
